### ISSUE TITLE
List of proposed things to try

### ISSUE THREAD

**Issue by hagata** [hagata/30daysofHelloWorld#1]
The following is a list of things to consider trying.
# Frameworks and things:

- Alexa
- ~Angular 2~ **Day 9**
- ~Architect~ **Day 6**
- Derby
- ~Django~ **Day 5**
- ~Ember~ **Day 11**
- ~Facebook Messenger~ **Day 24**
- ~Hapi.js~ **Day 2**
- ~Hug~ **Day 4**
- ~Ionic~ **Day 22**
- ~Koa~ **Day 3**
- Masonry
- Mean.js
- ~Meteor~ **Day 23**
- ~mo.js~ **Day 29**
- ~Next.js~ **Day 12**
- ~Polymer~ **Day 25**
- Raspberry Pi
- ~React Native~ **Day 10**
- ~Service Worker~ **Day 26**
- ~Socket.io~ **Day 15**
- ~Total.js~ **Day 28**
- Travis CI
- Twilio
- ~Vue.js~ **Day 7**
- Watson

# Gaming

- ~Matter.js~ **Day 16**
- Melon.js
- ~Phaser~ **Day 18**
- Physics.js

# Languages:

- Android Studio (Java)
- Awk
- Clojure
- ~Elm-lang~ **Day 20**
- ~Erlang~ **Day 21**
- ~Go~ **Day 1**
- ~Haskell~ **Day 14**
- Java + Spring
- ~MicroPython~ **Day 30**
- Perl
- Purescript
- ~R~ **Day 13**
- ~Rust~ **Day 19**
- Swagger
- ~Swift 3~ **Day 27**
- ~Typescript~ **Day 8**

# Tooling
- ~brunch.io~ **Day 17**

**Comment by hagata** [comment]
✨ Finished 30 for 2016! 🔥

**Comment by prilandini** [comment]
may i ask, How you learn one language in one day? You spend the whole day? whether by reading and practice it?
